import { useState, useEffect } from 'react';

export default function OutputDisplay({ output, isLoading, error, onRegenerate, onRetry, onSubmitFeedback }) {
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);
  
  // Feedback rating states
  const [rating, setRating] = useState(0);
  const [hoverRating, setHoverRating] = useState(0);
  const [comment, setComment] = useState('');
  const [feedbackSubmitted, setFeedbackSubmitted] = useState(false);

  // Reset local feedback form when output changes
  useEffect(() => {
    setRating(0);
    setHoverRating(0);
    setComment('');
    setFeedbackSubmitted(false);
  }, [output?.id]);

  // Copy Translation to Clipboard
  const handleCopyText = async () => {
    if (!output?.telugu_translation) return;
    try {
      await navigator.clipboard.writeText(output.telugu_translation);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy text:", err);
    }
  };

  // Share Formatted Translation Card to Clipboard
  const handleShareTranslation = async () => {
    if (!output) return;
    const notesText = output.cultural_notes && output.cultural_notes.length > 0
      ? "\nCultural & Phrasing Adjustments:\n" + output.cultural_notes.map(note => `- ${note}`).join('\n')
      : "";
    const cardContent = `📰 Telangana Today Localisation Report
---------------------------------------------
Journalist: ${output.journalist}
Style Tone: ${output.tone} | Regional Dialect: ${output.dialect}
Timestamp: ${new Date(output.timestamp).toLocaleString()}

Original English Draft:
"${output.english}"

Telugu Localised Translation:
"${output.telugu_translation}"
${notesText}
---------------------------------------------
Generated via Telangana Today Editorial AI.`;

    try {
      await navigator.clipboard.writeText(cardContent);
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    } catch (err) {
      console.error("Failed to copy share text:", err);
    }
  };

  // Download Telugu translation & notes as a text file
  const handleDownloadTxt = () => {
    if (!output?.telugu_translation) return;
    const notesText = output.cultural_notes && output.cultural_notes.length > 0
      ? "\n\nCULTURAL & PHRASING ADJUSTMENTS:\n" + output.cultural_notes.map(note => `- ${note}`).join('\n')
      : "";
    const content = `TELUGU TRANSLATION:\n${output.telugu_translation}${notesText}\n\nGenerated by ${output.journalist} on ${new Date(output.timestamp).toLocaleString()}\nTone: ${output.tone} | Dialect: ${output.dialect}`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `telangana_today_translation_${output.id || 'export'}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Print Formatted Localisation Report as PDF (Preserves Telugu Unicode font mappings)
  const handleDownloadPdf = () => {
    if (!output) return;
    
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert("Please allow popups to download PDF reports.");
      return;
    }

    const notesList = output.cultural_notes && output.cultural_notes.length > 0
      ? output.cultural_notes.map(note => `<li>${note}</li>`).join('')
      : "<li>No special phrasing notes logged.</li>";

    printWindow.document.write(`
      <html>
        <head>
          <title>Telangana Today - Localisation Report</title>
          <style>
            body {
              font-family: 'Inter', 'Segoe UI', -apple-system, sans-serif;
              padding: 40px;
              color: #1e293b;
              line-height: 1.6;
              background-color: #ffffff;
            }
            .header-banner {
              border-bottom: 3px solid #3a86c8;
              padding-bottom: 20px;
              margin-bottom: 30px;
              display: flex;
              justify-content: space-between;
              align-items: center;
            }
            .logo-text {
              font-size: 1.5rem;
              font-weight: 800;
              color: #0b1329;
              letter-spacing: -0.02em;
            }
            .logo-subtitle {
              font-size: 0.8rem;
              color: #3a86c8;
              text-transform: uppercase;
              letter-spacing: 0.1em;
            }
            .meta-grid {
              display: grid;
              grid-template-columns: repeat(2, 1fr);
              gap: 10px;
              background-color: #f8fafc;
              border: 1px solid #e2e8f0;
              padding: 15px;
              border-radius: 8px;
              margin-bottom: 30px;
              font-size: 0.9rem;
            }
            .meta-item strong {
              color: #475569;
            }
            .section-card {
              border: 1px solid #e2e8f0;
              border-radius: 8px;
              padding: 20px;
              margin-bottom: 25px;
            }
            .section-title {
              font-size: 1.05rem;
              font-weight: 700;
              color: #0b1329;
              margin-top: 0;
              margin-bottom: 12px;
              border-left: 4px solid #3a86c8;
              padding-left: 10px;
              text-transform: uppercase;
              letter-spacing: 0.02em;
            }
            .content-text {
              font-size: 1rem;
              color: #334155;
              white-space: pre-wrap;
            }
            .telugu-text {
              font-size: 1.25rem;
              color: #0f172a;
              line-height: 1.8;
              font-family: 'Gautami', 'Nirmala UI', 'Peddana', sans-serif;
            }
            .notes-ul {
              margin: 0;
              padding-left: 20px;
              color: #475569;
              font-size: 0.95rem;
            }
            .notes-ul li {
              margin-bottom: 8px;
            }
            .footer-tag {
              text-align: center;
              margin-top: 50px;
              font-size: 0.8rem;
              color: #94a3b8;
              border-top: 1px solid #e2e8f0;
              padding-top: 15px;
            }
            @media print {
              body { padding: 0; }
              .header-banner { border-bottom-color: #000; }
            }
          </style>
        </head>
        <body>
          <div class="header-banner">
            <div>
              <div class="logo-text">Telangana Today</div>
              <div class="logo-subtitle">Editorial Localisation Service</div>
            </div>
            <div style="text-align: right; font-size: 0.85rem; color: #64748b;">
              Report ID: ${output.id.substring(0, 8)}
            </div>
          </div>

          <div class="meta-grid">
            <div class="meta-item"><strong>Journalist:</strong> ${output.journalist}</div>
            <div class="meta-item"><strong>Uptime Latency:</strong> ${output.response_time_ms} ms</div>
            <div class="meta-item"><strong>Style Tone:</strong> ${output.tone}</div>
            <div class="meta-item"><strong>Regional Dialect:</strong> ${output.dialect}</div>
            <div class="meta-item" style="grid-column: span 2;"><strong>Generated On:</strong> ${new Date(output.timestamp).toLocaleString()}</div>
          </div>

          <div class="section-card">
            <div class="section-title">Original English Draft</div>
            <div class="content-text">${output.english}</div>
          </div>

          <div class="section-card" style="background-color: #fafaf9; border-color: #e7e5e4;">
            <div class="section-title" style="border-left-color: #06d6a0;">Telugu Localised Output</div>
            <div class="content-text telugu-text">${output.telugu_translation}</div>
          </div>

          <div class="section-card">
            <div class="section-title">Editorial Phrasing Adjustments</div>
            <ul class="notes-ul">
              ${notesList}
            </ul>
          </div>

          <div class="footer-tag">
            © 2026 Telangana Today Media Publications. Generated securely.
          </div>

          <script>
            setTimeout(function() {
              window.print();
              window.close();
            }, 250);
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  // Handle Feedback Submission
  const handleFeedbackSubmit = async (e) => {
    e.preventDefault();
    if (rating === 0) return;
    
    if (onSubmitFeedback) {
      const success = await onSubmitFeedback(output.id, rating, comment);
      if (success) {
        setFeedbackSubmitted(true);
      } else {
        alert("Failed to submit feedback. Please ensure the backend is running.");
      }
    }
  };

  // 1. Loading State
  if (isLoading) {
    return (
      <div className="glass-panel output-card" style={{ justifyContent: 'center', alignItems: 'center' }}>
        <div className="pulse-loader">
          <div className="output-placeholder-icon" style={{ opacity: 0.8 }}>⚡</div>
          <h3 style={{ marginBottom: '0.5rem', color: 'var(--accent-teal)' }}>Consulting AI Assistant</h3>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>Analyzing English syntax and mapping local phrasing...</p>
        </div>
      </div>
    );
  }

  // 2. Error State
  if (error) {
    return (
      <div className="glass-panel output-card" style={{ justifyContent: 'center', alignItems: 'center' }}>
        <div style={{ textAlign: 'center', color: 'var(--accent-coral)' }}>
          <div className="output-placeholder-icon" style={{ opacity: 0.8, color: 'var(--accent-coral)' }}>⚠️</div>
          <h3 style={{ marginBottom: '0.5rem' }}>Adaptation Failed</h3>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>{error}</p>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-dim)' }}>Please check your server connection or try again.</p>
          {onRetry && (
            <button
              id="btn-retry-generation"
              className="btn btn-secondary"
              style={{ width: 'auto', padding: '0.5rem 1.5rem', marginTop: '1.2rem', borderColor: 'var(--accent-coral)', color: 'var(--accent-coral)' }}
              onClick={onRetry}
            >
              🔄 Retry Request
            </button>
          )}
        </div>
      </div>
    );
  }

  // 3. Empty State (No output generated yet)
  if (!output) {
    return (
      <div className="glass-panel output-card">
        <div className="output-placeholder">
          <div className="output-placeholder-icon">📰</div>
          <h3 style={{ color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>Adaptation Output</h3>
          <p style={{ fontSize: '0.9rem', maxWidth: '300px' }}>Fill in the story details and click "Adapt to Telugu" to view localized results.</p>
        </div>
      </div>
    );
  }

  // Check if this record already has saved feedback
  const existingFeedback = output.feedback;

  // 4. Content State
  return (
    <div className="glass-panel output-card" id="output-display-panel">
      {/* Title Bar */}
      <div className="output-title-bar">
        <div>
          <h3 style={{ color: 'var(--accent-teal)' }}>Telugu Adaptation</h3>
          <span style={{ fontSize: '0.78rem', color: 'var(--text-dim)' }}>
            Rendered in {output.response_time_ms}ms | Tone: {output.tone} | Dialect: {output.dialect}
          </span>
        </div>
        <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
          <button
            id="btn-regenerate-translation"
            className="btn-copy"
            style={{ borderColor: 'var(--accent-teal)', color: 'var(--accent-teal)', background: 'rgba(0, 245, 212, 0.05)' }}
            onClick={onRegenerate}
          >
            🔄 Regenerate
          </button>
          <button
            id="btn-copy-translation"
            className="btn-copy"
            onClick={handleCopyText}
          >
            {copied ? "✓ Copied!" : "📋 Copy"}
          </button>
          <button
            id="btn-share-translation"
            className="btn-copy"
            style={{ borderColor: 'var(--accent-purple)', color: '#d8b4fe', background: 'rgba(114, 9, 183, 0.08)' }}
            onClick={handleShareTranslation}
          >
            {shared ? "✓ Shared!" : "🔗 Share"}
          </button>
          <button
            id="btn-download-txt"
            className="btn-copy"
            style={{ borderColor: 'rgba(255, 255, 255, 0.2)', color: 'var(--text-secondary)', background: 'transparent' }}
            onClick={handleDownloadTxt}
          >
            📄 TXT
          </button>
          <button
            id="btn-download-pdf"
            className="btn-copy"
            style={{ borderColor: 'rgba(58, 134, 200, 0.3)', color: 'var(--accent-cyan)', background: 'rgba(58, 134, 200, 0.1)' }}
            onClick={handleDownloadPdf}
          >
            📕 PDF
          </button>
        </div>
      </div>

      {/* Main Telugu Translation */}
      <div className="output-result-box" id="result-telugu-text">
        {output.telugu_translation}
      </div>

      {/* Telugu Translation Metrics */}
      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '1rem', fontSize: '0.78rem', color: 'var(--text-dim)', marginTop: '-1.2rem', marginBottom: '1.2rem', paddingRight: '0.2rem' }}>
        <span>Characters: {output.telugu_translation.length}</span>
        <span>Words: {output.telugu_translation.trim() === '' ? 0 : output.telugu_translation.trim().split(/\s+/).length}</span>
      </div>

      {/* Cultural Adaptation Notes */}
      {output.cultural_notes && output.cultural_notes.length > 0 && (
        <div className="notes-section" id="result-cultural-notes" style={{ marginBottom: '2rem' }}>
          <h4 className="notes-title">Cultural & Phrasing Adjustments</h4>
          <ul className="notes-list">
            {output.cultural_notes.map((note, index) => (
              <li key={index}>{note}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Rating & Feedback Section (Day 16 Milestone) */}
      <div className="feedback-section glass-panel" style={{ padding: '1.2rem', marginTop: '1rem', border: '1px dashed rgba(0, 245, 212, 0.2)', background: 'rgba(11, 19, 41, 0.4)' }}>
        <h4 style={{ fontSize: '0.92rem', color: 'var(--accent-teal)', marginBottom: '0.6rem', fontFamily: 'var(--font-display)' }}>Quality Assessment</h4>
        
        {existingFeedback || feedbackSubmitted ? (
          <div id="feedback-success-state" style={{ color: 'var(--accent-emerald)', fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span>✓</span>
            <span>
              Rating logged: <strong>{existingFeedback ? existingFeedback.rating : rating}/5 Stars</strong> 
              { (existingFeedback?.comment || comment) && ` - "${existingFeedback ? existingFeedback.comment : comment}"` }
            </span>
          </div>
        ) : (
          <form onSubmit={handleFeedbackSubmit} id="feedback-rating-form">
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.8rem', marginBottom: '0.8rem' }}>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Score translation:</span>
              <div style={{ display: 'flex', gap: '0.3rem' }} id="star-rating-container">
                {[1, 2, 3, 4, 5].map((star) => (
                  <button
                    key={star}
                    id={`star-button-${star}`}
                    type="button"
                    style={{
                      background: 'none',
                      border: 'none',
                      fontSize: '1.3rem',
                      cursor: 'pointer',
                      color: star <= (hoverRating || rating) ? 'var(--accent-teal)' : 'var(--text-dim)',
                      transition: 'color 0.15s ease'
                    }}
                    onMouseEnter={() => setHoverRating(star)}
                    onMouseLeave={() => setHoverRating(0)}
                    onClick={() => setRating(star)}
                  >
                    ★
                  </button>
                ))}
              </div>
            </div>
            
            {rating > 0 && (
              <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: '0.8rem', alignItems: 'end' }}>
                <input
                  id="input-feedback-comment"
                  type="text"
                  className="form-input"
                  placeholder="Optional editor comments..."
                  style={{ padding: '0.4rem 0.8rem', fontSize: '0.82rem', height: '32px' }}
                  value={comment}
                  onChange={(e) => setComment(e.target.value)}
                />
                <button
                  id="btn-submit-feedback"
                  type="submit"
                  className="btn btn-primary"
                  style={{ width: 'auto', padding: '0 1.2rem', height: '32px', fontSize: '0.82rem' }}
                >
                  Submit
                </button>
              </div>
            )}
          </form>
        )}
      </div>

      {/* Attribution Footer */}
      <div style={{ marginTop: '1.5rem', paddingTop: '1.2rem', borderTop: '1px solid rgba(255, 255, 255, 0.05)', fontSize: '0.78rem', color: 'var(--text-dim)', display: 'flex', justifyContent: 'space-between' }}>
        <span>Editor: {output.journalist}</span>
        <span>Generated: {new Date(output.timestamp).toLocaleTimeString()}</span>
      </div>
    </div>
  );
}
